name: book_finder_flutter_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^14.2.3
  intl: ^0.19.0
  dio: ^5.5.0+1
  infinite_scroll_pagination: ^4.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_native_splash:
  color: "#7264C2"
  image: assets/images/book_finder_logo.png

  android_12:
    image: assets/images/book_finder_logo.png
    image_dark: assets/images/book_finder_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/book_finder.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/book_finder.jpeg"
    background_color: "#ffd6d6d6"
    theme_color: "#ffd6d6d6"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf